Remove alt-arch config items that are not needed any more
openshift/library pull request #253
Opened 2020-09-15 15:52 UTC by hhorak

Related to https://github.com/sclorg/mongodb-container/pull/320 and https://github.com/sclorg/postgresql-container/pull/388 that remove the non-intel specific imagestreams.

2020-09-15 15:53 UTC, hhorak commented
@yselkowitz Running `make verify` did not work for me, so I'd welcome feedback if this is enough to be done once sclorg/mongodb-container#320 and sclorg/postgresql-container#388 are merged or something more needs to be done.

2020-09-15 15:56 UTC, gabemontero commented
> @yselkowitz Running `make verify` did not work for me, so I'd welcome feedback if this is enough to be done once [sclorg/mongodb-container#320](https://github.com/sclorg/mongodb-container/pull/320) and [sclorg/postgresql-container#388](https://github.com/sclorg/postgresql-container/pull/388) are merged or something more needs to be done.

it will a few hours from now @hhorak but I can check this PR out and try `make verify` as well ... based on what was deleted, I would think it would have worked.

@coreydaley FYI

2020-09-15 16:42 UTC, coreydaley commented
So, it looks like you need to run make import locally and commit the changes.  If you add or remove stuff from official.yaml, that is going to change what imagestreams and templates are present.

2020-09-15 19:01 UTC, yselkowitz requested changes
Arch tags are missing, and make import needs to be run and its results added to the commit.  Then make verify should pass.

2020-09-15 19:01 UTC, yselkowitz commented
/hold

2020-09-15 19:21 UTC, gabemontero commented
thanks @coreydaley @yselkowitz for beating me to the punch and sorting our the additional step @hhorak needs to execute

2020-09-16 06:21 UTC, hhorak commented
I should have shared more info right from beginning -- `make import` does not work because I don't have `./library` binary and when trying to build it, `make build` fails with:
```
$ make build
go version go1.14.4 gccgo (GCC) 10.2.1 20200723 (Red Hat 10.2.1-1) linux/amd64
go build -mod=vendor -race
package github.com/openshift/library
	imports runtime/race: cannot find package
make: *** [Makefile:34: build] Error 1
```
I did run `make vendor` before, which succeeded, but it doesn't help. I'm not a golang developer, so I might miss some basic thing here. Any hint?

2020-09-16 13:26 UTC, yselkowitz commented
Looks like you have gccgo instead of golang as your /usr/bin/go.  Either use golang, or just run `go build -mod=vendor` (without `-race`) manually.

2020-09-16 15:35 UTC, yselkowitz commented
@hhorak if you `git pull --rebase` now, make build might work with gccgo now.

2020-09-17 14:31 UTC, hhorak commented
I installed golang and it worked as well, thanks for the suggestion. The PR is now updated with the imported files. There is one more PR not merged (https://github.com/sclorg/django-ex/pull/164) but I guess it doesn't block this PR, because it will be updated by the script once merged. Hope this PR is good now.

2020-09-17 14:32 UTC, hhorak commented
Hups, sorry, arch tags are still missing, fixing right away..

2020-09-17 14:34 UTC, hhorak commented on official.yaml
>            - online-professional
Fixed now.

2020-09-17 14:34 UTC, hhorak commented on official.yaml
>            - online-professional
Fixed now.

2020-09-17 14:34 UTC, hhorak commented
> Hups, sorry, arch tags are still missing, fixing right away..

Fixed now.

2020-09-17 14:51 UTC, gabemontero commented
/hold cancel

/approve 

So assuming the test jobs pass now, I see deletes.  And when I look at some of the files htat were changed, I still see the *-ubi8 and *-ubi7 pattern that has been recently established.

That said, while I've approved this, if possible @yselkowitz since you are most familiar with our shift here, I'd like for you to give this the final review.  If you are good, I believe with my approve, you lgtm (using / to add the label) should be sufficient to merge this.

thanks everyone

2020-09-17 14:51 UTC, gabemontero commented
and the tests passed while I was typing the last comment :-)

2020-09-17 15:02 UTC, yselkowitz commented
Thanks Honza this looks good now.
/lgtm

2020-09-17 15:06 UTC, merged