Updating imagestreams and templates for JWS 5.4
openshift/library pull request #265
Opened 2020-11-27 19:13 UTC by bekionel

This updates the RHEL7 imagestreams and templates for JWS 5.4 and also adds the UBI8 imagestreams and templates.
Removing outdated database templates for the time being.

2020-11-29 23:22 UTC, yselkowitz commented
This and #264 conflict due to affecting neighbouring lines.  Any reason not to combine them in one PR?  (Commits can stay separate though.)

2020-11-30 01:58 UTC, yselkowitz requested changes

2020-11-30 01:58 UTC, yselkowitz commented on official.yaml
> +        #tags:
Instead of commenting out these tags, maybe just delete them for now?  Since they're in a separate commit, then you can just revert them later if/when they're migrated to current versions of mysql and postgresql?

2020-11-30 15:03 UTC, gabemontero commented
From what I saw in comments in #264 that PR will pick up the changes from this one

/close

we can reopen this later if that approach has to change

2020-11-30 15:03 UTC, closed without merging