Add EAP XP 4.0
openshift/library pull request #310
Opened 2022-05-11 15:07 UTC by luck3y

https://issues.redhat.com/browse/JBEAP-23231
Signed-off-by: kwills@redhat.com

2022-05-13 15:54 UTC, yselkowitz requested changes
Found some non-groupified API references that need to be fixed in your own repo and re-imported.

2022-05-13 15:54 UTC, yselkowitz commented on official/eap/templates/eap-xp4-basic-s2i.json
> +			"apiVersion": "v1",
Please fix in your upstream:
```suggestion
			"apiVersion": "route.openshift.io/v1",
```

2022-05-13 15:54 UTC, yselkowitz commented on official/eap/templates/eap-xp4-basic-s2i.json
> +			"apiVersion": "v1",
Please fix in your upstream:
```suggestion
			"apiVersion": "build.openshift.io/v1",
```

2022-05-13 15:54 UTC, yselkowitz commented on official/eap/templates/eap-xp4-basic-s2i.json
> +			"apiVersion": "v1",
Please fix in your upstream:
```suggestion
			"apiVersion": "build.openshift.io/v1",
```

2022-05-13 15:54 UTC, yselkowitz commented on official/eap/templates/eap-xp4-basic-s2i.json
> +			"apiVersion": "v1",
Ditto.

2022-05-13 15:54 UTC, yselkowitz commented on official/eap/templates/eap-xp4-basic-s2i.json
> +			"apiVersion": "v1",
Ditto.

2022-05-13 15:54 UTC, yselkowitz commented on official/eap/templates/eap-xp4-basic-s2i.json
> +			"apiVersion": "v1",
Please fix in your upstream:
```suggestion
			"apiVersion": "apps.openshift.io/v1",
```

2022-05-13 15:54 UTC, yselkowitz commented on official/eap/templates/eap-xp4-basic-s2i.json
> +			"apiVersion": "v1",
Please fix in your upstream:
```suggestion
			"apiVersion": "apps.openshift.io/v1",
```

2022-05-13 16:03 UTC, dperaza4dustbit commented
Hello @luck3y I see that EAP XP 3 is already added as a helm chart in our OpenShift Repository. Do you need it in the cluster as both sample and helm chart? What would be the use case for that? Depending on the answer can you consider adding EAP XP 4 as another helm chart in the certification repo: https://github.com/openshift-helm-charts/charts/tree/main/charts/redhat/redhat. These are the owners for EAP XP 3: https://github.com/openshift-helm-charts/charts/blob/main/charts/redhat/redhat/eap-xp3/OWNERS

2022-05-13 18:45 UTC, luck3y commented
> Found some non-groupified API references that need to be fixed in your own repo and re-imported.

Thanks @yselkowitz, I thought I'd already checked those, will update.

2022-05-13 18:46 UTC, luck3y commented
@dperaza4dustbit I'll need to get @jmesnil's feedback on what we should do here, thanks for raising the issue though.

2022-05-16 06:37 UTC, jmesnil commented
@dperaza4dustbit Thanks for raising this issue. We are planning to put a Helm Chart for EAP XP 4 in OpenShift library soon (they are still in Tech Preview fwiw)
However we have not yet stop supporting OpenShift templates for EAP XP products, so we would like to have both available in OpenShift.

Please note this would be the last time we would have both: next versions of EAP will only provided (supported) Helm Charts.

2022-05-24 13:53 UTC, luck3y commented
@gabemontero @yselkowitz This has been addressed in the source repo and updated, thanks for the feedback!

2022-05-24 14:12 UTC, yselkowitz approved these changes
/lgtm
/assign @dperaza4dustbit

2022-05-24 15:08 UTC, dperaza4dustbit commented
/approve

2022-05-24 15:42 UTC, merged