[RHPAM-4503] Remove RHPAM templates from OCP 4 catalog
openshift/library pull request #336
Opened 2022-10-04 11:39 UTC by davidesalerno

Signed-off-by: Davide Salerno <dsalerno@redhat.com>

I checked that everything is working executing these steps:

1. make build
2. make import
3. make verify (finished successfully for both official and community library)

2022-10-04 12:26 UTC, spolti commented
@fbm3307 fyi

2022-10-04 12:37 UTC, spolti commented on official.yaml
>    rhpam:
we can remove this entire section.

2022-10-04 13:04 UTC, spolti requested changes
Many thanks @davidesalerno , just a few comments.

2022-10-04 13:04 UTC, spolti commented on official.yaml
>    rhpam:
please also remove the `  ips_ds_version` sections and envs from the beginning of this file.

2022-10-10 06:52 UTC, fbm3307 commented
/ok-to-test

2022-10-10 06:55 UTC, fbm3307 commented
@davidesalerno would you please update as per @spolti's cooments.?

2022-10-10 09:19 UTC, davidesalerno commented
@fbm3307 yes

2022-10-10 09:29 UTC, fbm3307 commented
/retest

2022-10-10 12:40 UTC, spolti commented on official.yaml
>    rhpam_version: 7.12.1.GA
you missed this one.

2022-10-10 12:41 UTC, spolti commented on official.yaml
>    rhpam:
you missed this part as well.

2022-10-11 06:38 UTC, davidesalerno commented on official.yaml
>    rhpam_version: 7.12.1.GA
Do we need to remove also the rhpam section & variables?

2022-10-11 12:56 UTC, spolti commented on official.yaml
>    rhpam_version: 7.12.1.GA
Yes.

2022-10-11 13:12 UTC, davidesalerno commented
@fbm3307 We also cleaned up the arch path from folders related to rhdm | decisionserver | processerver | rhpam.
Is it that fine?

2022-10-13 11:15 UTC, dperaza4dustbit approved these changes
/lgtm

2022-10-13 11:17 UTC, fbm3307 commented
> @fbm3307 We also cleaned up the arch path from folders related to rhdm | decisionserver | processerver | rhpam. Is it that fine?

@davidesalerno yes it is fine and Thanks for this @spolti appreciate your help on this

2022-10-13 11:22 UTC, merged